"""users表增加PC端背景图片字段

Revision ID: da589f891f75
Revises: 9ccbee803e77
Create Date: 2026-02-04 22:56:19.909810

"""

# revision identifiers, used by Alembic.
revision = 'da589f891f75'
down_revision = '9ccbee803e77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pc_bg_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pc_bg_image')
    # ### end Alembic commands ###
